from __future__ import annotations

QUEUED = "QUEUED"
UPLOADING = "UPLOADING"
READY = "READY"
FIRST_FRAME = "FIRST FRAME"
GENERATING = "GENERATING"
UPSCALING = "UPSCALING"
ENCODING = "ENCODING"
UPLOADING_TO_DRIVE = "UPLOADING TO DRIVE"
COMPLETED = "COMPLETED"
FAILED = "FAILED"

ACTIVE_STATES = {
    UPLOADING,
    READY,
    FIRST_FRAME,
    GENERATING,
    UPSCALING,
    ENCODING,
    UPLOADING_TO_DRIVE,
}

TERMINAL_STATES = {COMPLETED, FAILED}
